- name: installing python 
  ansible.builtin.yum:
    name: "{{item}}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel
- name: setting app directory
  import_role:
    name: common
    tasks_from: setup-app.yaml 
- name: Change the working directory to app and install dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app    
- name: setting systemd from common tasks
  import_role:
    name: common
    tasks_from: setup-systemd.yaml        


