- name: copying rabbitmq.repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: installing rabbitmq-server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: present

- name: starting and enabling rabbitmq
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started
    enabled: true  

- name: Adding roboshop user in RabbitMQ
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    state: present
    force: yes

- name: Setting permissions for roboshop user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
