
    - name: installing mysql
      ansible.builtin.yum:
        name: mysql-server
        state: present
    
    - name: starting and enabling mysql
      ansible.builtin.systemd_service:
        state: started
        name: mysqld
        enabled: true   
    - name: changing the password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1        

       